    CREATE TABLE TB_USUARIO(
    UUID_USUARIO VARCHAR2(50) PRIMARY KEY,
    NOMBRE_DE_USUARIO VARCHAR2(50) NOT NULL,
    CONTRASENA VARCHAR2(50) NOT NULL
    );
    
    CREATE TABLE TB_TICKET(
    NUMERO_DE_TICKET VARCHAR2(50) PRIMARY KEY,
    TITULO VARCHAR2(50) NOT NULL,
    DESCRIPCION VARCHAR2(150) NOT NULL,
    AUTOR VARCHAR2(50) NOT NULL,
    EMAIL_AUTOR VARCHAR2(50) NOT NULL,
    FECHA_DE_CREACION DATE NOT NULL,
    ESTADO VARCHAR2(10) CHECK (ESTADO IN ('Activo', 'Finalizado')),
    FECHA_DE_FINALIZACION DATE);